// apps/react-app/src/app/app.tsx
import {
  PfButton,
  PfCheckbox,
  PfImage,
  PfSelect,
} from '@profabric/react-components';
import { useState } from 'react';
import _ from 'lodash';

const themes = [
  'primary',
  'secondary',
  'success',
  'danger',
  'warning',
  'info',
  'dark',
  'light',
  'link',
];

export function App() {
  const [buttons, setButtons] = useState([
    themes.map((t) => ({
      theme: t,
      text: t.charAt(0).toUpperCase() + t.slice(1).toLowerCase(),
      loading: false,
      size: 'default',
    })),
    themes.map((t) => ({
      theme: t,
      text: t.charAt(0).toUpperCase() + t.slice(1).toLowerCase(),
      loading: false,
      size: 'small',
    })),
    themes.map((t) => ({
      theme: t,
      text: t.charAt(0).toUpperCase() + t.slice(1).toLowerCase(),
      loading: false,
      size: 'large',
    })),
  ]);
  const [selects] = useState([
    {
      options: themes.map((t) => ({
        label: t.charAt(0).toUpperCase() + t.slice(1).toLowerCase(),
        value: t,
      })),
      label: 'Small',
      size: 'small',
    },
    {
      options: themes.map((t) => ({
        label: t.charAt(0).toUpperCase() + t.slice(1).toLowerCase(),
        value: t,
      })),
      label: 'Default',
      size: 'default',
    },
    {
      options: themes.map((t) => ({
        label: t.charAt(0).toUpperCase() + t.slice(1).toLowerCase(),
        value: t,
      })),
      label: 'Large',
      size: 'large',
    },
  ]);
  const [checkboxes] = useState([
    {
      label: 'Checkbox',
      switchable: false,
    },
    {
      label: 'Switch',
      switchable: true,
    },
  ]);
  const [timeoutID, setTimeoutID] = useState<NodeJS.Timeout | null>(null);

  const handleClick = (item: any) => {
    if (timeoutID) {
      clearTimeout(timeoutID);
    }

    setButtons(
      buttons.map((chunk) =>
        chunk.map((c) => ({ ...c, loading: _.isEqual(c, item) }))
      )
    );

    const tID: NodeJS.Timeout = setTimeout(() => {
      setButtons(
        buttons.map((chunk) => chunk.map((c) => ({ ...c, loading: false })))
      );
    }, 3000);

    setTimeoutID(tID);
  };

  return (
    <div className="container mt-5">
      <h1 className="mb-4">Buttons</h1>
      {buttons.map((chunk, index) => (
        <div key={index} className="row gx-2 mb-3">
          {chunk.map((c) => (
            <PfButton
              key={c.theme}
              className="col"
              block
              theme={c.theme as any}
              size={c.size as any}
              loading={c.loading}
              onClick={() => handleClick(c)}
            >
              {c.text}
            </PfButton>
          ))}
        </div>
      ))}

      <div className="row gx-2 mb-3">
        {selects.map((select) => (
          <PfSelect
            key={select.label}
            className="col"
            label={select.label}
            options={select.options}
            size={select.size as any}
            onChange={(e: any) => console.log(e.target.value)}
          />
        ))}
      </div>
      <div className="row gx-2 mb-3">
        {checkboxes.map((checkbox) => (
          <PfCheckbox
            key={checkbox.label}
            className="col"
            switchable={checkbox.switchable}
            onChange={(e: any) => console.log(e.target.checked)}
          >
            {checkbox.label}
          </PfCheckbox>
        ))}
      </div>
      <div className="row gx-2 mb-3">
        <PfImage width={120} height={120} />
      </div>
    </div>
  );
}

export default App;

// apps/angular-app/src/app/app.component.ts
import { Component } from '@angular/core';
import * as _ from 'lodash';

@Component({
  selector: 'profabric-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  title = 'angular-app';
  public themes = [
    'primary',
    'secondary',
    'success',
    'danger',
    'warning',
    'info',
    'dark',
    'light',
    'link',
  ];
  public buttons = [
    this.themes.map((t) => ({
      theme: t,
      text: t.charAt(0).toUpperCase() + t.slice(1).toLowerCase(),
      loading: false,
      size: 'default',
    })),
    this.themes.map((t) => ({
      theme: t,
      text: t.charAt(0).toUpperCase() + t.slice(1).toLowerCase(),
      loading: false,
      size: 'small',
    })),
    this.themes.map((t) => ({
      theme: t,
      text: t.charAt(0).toUpperCase() + t.slice(1).toLowerCase(),
      loading: false,
      size: 'large',
    })),
  ];
  public selects: Array<any> = [
    {
      options: this.themes.map((t) => ({
        label: t.charAt(0).toUpperCase() + t.slice(1).toLowerCase(),
        value: t,
      })),
      label: 'Small',
      size: 'small',
    },
    {
      options: this.themes.map((t) => ({
        label: t.charAt(0).toUpperCase() + t.slice(1).toLowerCase(),
        value: t,
      })),
      label: 'Default',
      size: 'default',
    },
    {
      options: this.themes.map((t) => ({
        label: t.charAt(0).toUpperCase() + t.slice(1).toLowerCase(),
        value: t,
      })),
      label: 'Large',
      size: 'large',
    },
  ];
  public checkboxes: Array<any> = [
    {
      label: 'Checkbox',
      switchable: false,
    },
    {
      label: 'Switch',
      switchable: true,
    },
  ];
  public timeoutID: any = null;

  public handleClick(item: any) {
    if (this.timeoutID) {
      clearTimeout(this.timeoutID);
    }

    this.buttons = this.buttons.map((chunk) =>
      chunk.map((c) => ({ ...c, loading: _.isEqual(c, item) }))
    );

    this.timeoutID = setTimeout(() => {
      this.buttons = this.buttons.map((chunk) =>
        chunk.map((c) => ({ ...c, loading: false }))
      );
    }, 50000);
  }

  public handleOnSelectChange(event: any) {
    console.log(event.target.value);
  }

  public handleOnCheckboxChange(event: any) {
    console.log(event.target.checked);
  }
}

<div class="container mt-5">
  <h1 class="mb-4">Buttons</h1>
  <div *ngFor="let chunk of buttons" class="row gx-2 mb-3">
    <pf-button
      *ngFor="let c of chunk"
      class="col"
      block
      [theme]="c.theme"
      [size]="c.size"
      [loading]="c.loading"
      (click)="handleClick(c)"
    >
      {{ c.text }}
    </pf-button>
  </div>

  <div class="row gx-2 mb-3">
    <pf-select
      class="col"
      *ngFor="let component of selects"
      [label]="component.label"
      [options]="component.options"
      [size]="component.size"
      (change)="handleOnSelectChange($event)"
    ></pf-select>
  </div>
  <div class="row gx-2 mb-3">
    <pf-checkbox
      class="col"
      *ngFor="let checkbox of checkboxes"
      [switchable]="checkbox.switchable"
      (change)="handleOnCheckboxChange($event)"
    >
      {{ checkbox.label }}</pf-checkbox
    >
  </div>
  <div class="row gx-2 mb-3">
    <pf-image class="my-image" width="200" height="200" rounded> </pf-image>
  </div>
</div>
