// packages/react-app/src/app/app.tsx
import { PfButton } from '@profabric/react-components';
import { useState } from 'react';
import _ from 'lodash';

const themes = [
  'primary',
  'secondary',
  'success',
  'danger',
  'warning',
  'info',
  'dark',
  'light',
  'link',
];

export function App() {
  const [components, setComponents] = useState([
    themes.map((t) => ({
      theme: t,
      text: t.charAt(0).toUpperCase() + t.slice(1).toLowerCase(),
      loading: false,
      size: 'default',
    })),
    themes.map((t) => ({
      theme: t,
      text: t.charAt(0).toUpperCase() + t.slice(1).toLowerCase(),
      loading: false,
      size: 'small',
    })),
    themes.map((t) => ({
      theme: t,
      text: t.charAt(0).toUpperCase() + t.slice(1).toLowerCase(),
      loading: false,
      size: 'large',
    })),
  ]);

  const handleClick = (item: any) => {
    setComponents(
      components.map((chunk) =>
        chunk.map((c) => ({ ...c, loading: _.isEqual(c, item) }))
      )
    );

    setTimeout(() => {
      setComponents(
        components.map((chunk) => chunk.map((c) => ({ ...c, loading: false })))
      );
    }, 3000);
  };

  return (
    <div className="container mt-5">
      <h1 className="mb-4">Buttons</h1>
      {components.map((chunk) => (
        <div className="row mb-3">
          {chunk.map((c) => (
            <PfButton
              className="col"
              block
              theme={c.theme as any}
              size={c.size as any}
              loading={c.loading}
              onClick={() => handleClick(c)}
            >
              {c.text}
            </PfButton>
          ))}
        </div>
      ))}
    </div>
  );
}

export default App;

// packages/angular-app/src/app/app.component.ts
import { Component } from '@angular/core';
import * as _ from 'lodash';

@Component({
  selector: 'profabric-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  title = 'angular-app';
  public themes = [
    'primary',
    'secondary',
    'success',
    'danger',
    'warning',
    'info',
    'dark',
    'light',
    'link',
  ];
  public components = [
    this.themes.map((t) => ({
      theme: t,
      text: t.charAt(0).toUpperCase() + t.slice(1).toLowerCase(),
      loading: false,
      size: 'default',
    })),
    this.themes.map((t) => ({
      theme: t,
      text: t.charAt(0).toUpperCase() + t.slice(1).toLowerCase(),
      loading: false,
      size: 'small',
    })),
    this.themes.map((t) => ({
      theme: t,
      text: t.charAt(0).toUpperCase() + t.slice(1).toLowerCase(),
      loading: false,
      size: 'large',
    })),
  ];
  public timeoutID: any = null;

  public handleClick(item: any) {
    if (this.timeoutID) {
      clearTimeout(this.timeoutID);
    }

    this.components = this.components.map((chunk) =>
      chunk.map((c) => ({ ...c, loading: _.isEqual(c, item) }))
    );

    this.timeoutID = setTimeout(() => {
      this.components = this.components.map((chunk) =>
        chunk.map((c) => ({ ...c, loading: false }))
      );
    }, 50000);
  }
}

<div class="container mt-5">
  <h1 class="mb-4">Buttons</h1>
  <div *ngFor="let chunk of components" class="row gx-2 mb-3">
    <pf-button
      *ngFor="let c of chunk"
      class="col"
      block
      [theme]="c.theme"
      [size]="c.size"
      [loading]="c.loading"
      (click)="handleClick(c)"
    >
      {{ c.text }}
    </pf-button>
  </div>
</div>
